import {
  BarChart3,
  Wrench,
  Package,
  ClipboardCheck,
  Archive,
  Users,
  Settings,
  ShoppingCart,
  Lightbulb,
  FileSignature,
  Inbox,
  Briefcase,
  Award,
  GitMerge,
  ListChecks,
  MessageSquare,
  PieChart,
  Clipboard,
  Files,
  StickyNote,
  Factory,
  CalendarRange,
  Monitor,
  FlaskConical,
  Warehouse,
  Scale,
  ShieldCheck,
  Cog,
  FileText,
  Timer,
  GraduationCap,
  LineChart,
  Database,
  BookOpen,
  HardHat,
  Sliders,
  LayoutTemplate,
  FileSpreadsheet,
  AlertTriangle,
  History,
  FormInput,
  MapPin,
  Truck,
  Hammer,
  FilePlus2,
} from 'lucide-react';

/** منوی اصلی بدون «مدیریت اطلاعات پایه» — آن بخش فقط برای ادمین lazy-load می‌شود. */
export const MENU_ITEMS_CORE = [
  { id: 'dashboard', title: 'داشبورد', icon: BarChart3, path: '/' },

  {
    id: 'reports-group',
    title: 'گزارشات',
    icon: Files,
    path: '#',
    submenu: [
      { id: 'control-room', title: 'گزارش اتاق کنترل', icon: Monitor, path: '/control-room' },
      { id: 'shiftreport', title: 'گزارش شیفت', icon: Clipboard, path: '/shift-report' },
      { id: 'lab-report', title: 'گزارش آزمایشگاه', icon: FlaskConical, path: '/lab-report' },
      { id: 'scale-report', title: 'گزارش باسکول', icon: Scale, path: '/scale-report' },
      { id: 'productionreport', title: 'گزارش جامع تولید', icon: Factory, path: '/production-report' },
      { id: 'warehouse-report', title: 'گزارش انبار', icon: Warehouse, path: '/warehouse-report' },
      { id: 'hse-report', title: 'گزارش ایمنی و بهداشت', icon: HardHat, path: '/hse-report' },
      { id: 'reports', title: 'گزارش‌ساز پویا', icon: PieChart, path: '/reports' },
      { id: 'list-report', title: 'گزارش لیستی', icon: FileSpreadsheet, path: '/list-report' },
    ],
  },

  { id: 'work-calendar', title: 'تقویم کاری', icon: CalendarRange, path: '/work-calendar' },
  { id: 'inbox', title: 'کارتابل من', icon: Inbox, path: '/inbox' },
  { id: 'messages', title: 'پیام‌ها', icon: MessageSquare, path: '/messages' },
  { id: 'notes', title: 'یادداشت‌های من', icon: StickyNote, path: '/notes' },

  {
    id: 'maintenance-group',
    title: 'مدیریت نت',
    icon: Wrench,
    path: '#',
    submenu: [
      { id: 'workorders', title: 'دستور کارها', icon: ListChecks, path: '/work-orders' },
      { id: 'pm-scheduler', title: 'زمان‌بندی نت (PM)', icon: Timer, path: '/pm-scheduler' },
      { id: 'kpis', title: 'شاخص‌های فنی (KPI)', icon: LineChart, path: '/kpis' },
      { id: 'inspections', title: 'بازرسی فنی', icon: ClipboardCheck, path: '/inspections' },
      { id: 'service-repair', title: 'خدمات / تعمیرات', icon: Hammer, path: '/service-repair' },
    ],
  },

  {
    id: 'hse-group',
    title: 'ایمنی و بهداشت',
    icon: ShieldCheck,
    path: '#',
    submenu: [{ id: 'permits', title: 'مجوز کار (PTW)', icon: FileSignature, path: '/permits' }],
  },

  {
    id: 'engineering-group',
    title: 'دفتر فنی مهندسی',
    icon: Cog,
    path: '#',
    submenu: [
      { id: 'bom', title: 'درخت تجهیز (BOM)', icon: GitMerge, path: '/bom' },
      { id: 'projects', title: 'کنترل پروژه', icon: Briefcase, path: '/projects' },
      { id: 'documents', title: 'اسناد فنی', icon: Archive, path: '/documents' },
      { id: 'suggestions', title: 'پیشنهادات فنی', icon: Lightbulb, path: '/suggestions' },
      { id: 'meetings', title: 'صورتجلسات', icon: FileText, path: '/meetings' },
    ],
  },

  {
    id: 'supply-group',
    title: 'زنجیره تامین',
    icon: ShoppingCart,
    path: '#',
    submenu: [
      { id: 'inventory', title: 'موجودی انبار', icon: Warehouse, path: '/inventory' },
      { id: 'partrequest', title: 'درخواست کالا', icon: Package, path: '/part-requests' },
      { id: 'purchases', title: 'درخواست خرید', icon: ShoppingCart, path: '/purchases' },
      { id: 'factory-exit', title: 'خروج کالا از کارخانه', icon: Truck, path: '/factory-exit' },
    ],
  },

  {
    id: 'hr-group',
    title: 'اداری و پرسنلی',
    icon: Users,
    path: '#',
    submenu: [
      { id: 'training-courses', title: 'دوره‌های آموزشی', icon: BookOpen, path: '/training-courses' },
      { id: 'training', title: 'ماتریس مهارت و آموزش', icon: GraduationCap, path: '/training' },
      { id: 'performance', title: 'امتیاز عملکرد', icon: Award, path: '/performance' },
      { id: 'missions', title: 'مأموریت', icon: MapPin, path: '/missions' },
    ],
  },

  {
    id: 'system-settings',
    title: 'تنظیمات سیستم',
    icon: Settings,
    path: '#',
    role: 'ADMIN',
    submenu: [
      { id: 'app-config', title: 'تنظیمات نرم‌افزار', icon: Sliders, path: '/system-config' },
      { id: 'process-design', title: 'طراحی فرآیند', icon: GitMerge, path: '/process-design' },
      { id: 'process-form-design', title: 'طراحی فرم عملیاتی', icon: FormInput, path: '/process-form-design' },
      { id: 'workflow-design', title: 'طراحی گردش کار', icon: GitMerge, path: '/workflow-designer' },
      { id: 'report-design', title: 'طراحی گزارش', icon: FilePlus2, path: '/report-design' },
      { id: 'report-template-design', title: 'طراحی قالب گزارش', icon: LayoutTemplate, path: '/report-template-design' },
      { id: 'report-form-design', title: 'طراحی فرم گزارش', icon: FormInput, path: '/report-form-design' },
      { id: 'import-tool-settings', title: 'تنظیمات ابزار ورود اطلاعات', icon: FileSpreadsheet, path: '/data-entry-tool-settings' },
      { id: 'software-errors', title: 'خطاهای نرم‌افزار', icon: AlertTriangle, path: '/software-errors' },
      { id: 'data-change-tracking', title: 'ردیابی تغییرات اطلاعات', icon: History, path: '/data-change-tracking' },
      { id: 'integration', title: 'یکپارچه‌سازی (API)', icon: Database, path: '/integration' },
    ],
  },
  { id: 'settings', title: 'تنظیمات کاربری', icon: Settings, path: '/settings' },
];
